[package]
name = "hourglass"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", features = ["canvas"] }
iced_native = { git = "https://github.com/iced-rs/iced" }
iced_wgpu = { git = "https://github.com/iced-rs/iced" }
wasm-bindgen = "0.2.79"
